# MOVIELENS
library(readr)
ageTable = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/CLEAN_DATA/MOVIELENS/ageTable.csv", col_types = "?")
spec(ageTable)
genreTable = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/CLEAN_DATA/MOVIELENS/movieLensGenreTable.csv", col_types = "?")
spec(genreTable)
movies = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/CLEAN_DATA/MOVIELENS/movies.csv", col_types = "?")
spec(movies)
ratings = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/CLEAN_DATA/MOVIELENS/ratings.csv", col_types = "?")
spec(ratings)
users = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/CLEAN_DATA/MOVIELENS/users.csv", col_types = "?")
spec(users)
uszips = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/DATASETS/MOVIELENS/uszips.csv", col_types = "?") 
spec(uszips)
workTable = read_csv("C:/Elaborato-DataScience-2022/WEBSERVER/www/CLEAN_DATA/MOVIELENS/workTable.csv", col_types = "?")
spec(workTable)