---
title: "IMPORT DATA"
author: "Damiano Fumagalli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# INDEX

-   [AMAZON](https://www.kaggle.com/datasets/shivamb/amazon-prime-movies-and-tv-shows)

    -   TIDY

    -   TRANSFORM

-   [DISNEY+](https://www.kaggle.com/datasets/shivamb/disney-movies-and-tv-shows)

    -   TIDY

    -   TRANSFORM

-   [GROSS](https://www.kaggle.com/datasets/sanjeetsinghnaik/top-1000-highest-grossing-movies)

    -   TIDY

    -   TRANSFORM

-   [MOVIELENS](https://grouplens.org/datasets/movielens/1m/)

    -   TIDY

    -   TRANSFORM

-   [NETFLIX](https://www.kaggle.com/datasets/shivamb/netflix-shows)

    -   TIDY

    -   TRANSFORM

-   [OSCARS](https://www.kaggle.com/datasets/dharmikdonga/academy-awards-dataset-oscars)

    -   TIDY

    -   TRANSFORM

-   [SEQUELS](https://data.world/priyankad0993/sequels)

    -   TIDY

    -   TRANSFORM

### R CODE

```{r, eval=FALSE}
#eval = FALSE --> THE CODE CHUNK ISN'T EVALUATED

library(readr)

amazon  <- read_csv("../../DATASETS/AMAZON/amazon.csv")


disney <- read_csv("../../DATASETS/DISNEY/disney.csv")


HighestGrossers <- read_csv("../../DATASETS/GROSS/HighestGrossers.csv")


movies <- read_delim("../../DATASETS/MOVIELENS/movies.dat",delim = ';', col_names = c("movieID","Title","Genres"))

ratings <- read_csv("../../DATASETS/MOVIELENS/ratings.csv", col_names = c("userID","movieID","Rating","Timestamp"))

users <- read_csv("../../DATASETS/MOVIELENS/users.csv", col_names = c("UserID","Gender","Age","Occupation","Zip"), col_types = "?")
# USA ZIPCODES
uszips <- read_csv("../../DATASETS/MOVIELENS/uszips.csv")



netflix <- read_csv("../../DATASETS/NETFLIX/netflix.csv")


oscars <- read_csv("../../DATASETS/OSCARS/oscars.csv")


sequels <- read_delim("../../DATASETS/SEQUELS/sequels.csv",delim = ";")


tmdb <- read_csv("../../DATASETS/TMDB/tmdb.csv")


```
