---
title: "MOVIELENS"
author: "Damiano Fumagalli"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
# source("../../../R/cleanedData.R")
library(readr)
library(dplyr)
library(usmap)
library(ggplot2)
```

# INDICE

-   IMPORT DATA
-   RATING - OCCUPATION
-   MAPS

# IMPORT

```{r, echo=FALSE}
source("../IMPORT/dataScript/movielensData.r")
# DATASETS = movies, ratings, users, uszips, workTable, ageTable, MLGenres
```

### GENRE

```{r}
MLGenres$genre
```

### OCCUPATION {#occupation}

```{r}
workTable$workType
```

```{r}



favouriteGenre = function(occType){
  occID = workTable[workTable$workType == occType,]$workID
  userRatings = left_join(left_join(users %>% filter(occupation == occID),ratings, by = "userid"),movies,by = "movieid")
  prec = 0
  gen = ""
  for (i in 1:length(MLGenres$genre)){
    a = nrow(userRatings %>% filter(rating >= 4) %>% filter(grepl(MLGenres$genre[i],genres)) )
     
    if (a > prec) {
      prec = a
      gen = MLGenres$genre[i]
    }
  }
  return(gen)
}

dataF = data.frame(
  occupation = workTable$workType,
  favGen = unlist(lapply(workTable$workType, favouriteGenre))
  
)


OccIDtoType = function(ID){
  type = workTable[workTable$workID == ID,]$workType
  return (type)
}

dataF = inner_join(dataF,users %>% mutate(occupation = unlist(lapply(occupation, OccIDtoType))) %>% group_by(occupation) %>% summarise(nUsers = n()), by = "occupation")
head(dataF)

ggplot(dataF) + geom_col(aes(nUsers,occupation,fill = favGen)) 
```

# USER-LOCATIONS {#userLocation}

### [MAIN APP](../../)

```{r}
# choices = c(showMap, choiceParam)
usersMap = function(choices,param){  
  if (param  == "O"){
    occID = workTable[workTable$workType == choices[2],]$workID
    dati = left_join(users %>% filter(occupation == occID), ratings, by = "userid" ) %>% group_by(userid) %>% summarise(rating = mean(rating), zip = unique(zip)) 
    
    
    dati = dati %>% group_by(zip) %>% summarise(rating = mean(rating),userCount = n())
    
    
    
    dati = left_join(dati,uszips  ,by="zip") 
    dati = dati %>% filter(!is.na(lat))
    plot = plot_usmap(data = dati,values = "userCount",labels = (choices[1] == "YES") , label_color = "white")  +  scale_fill_continuous( low = "red", high = "green", name = paste(choices[2],"users count"), label = scales::comma ) + theme(legend.position = "right")
    
  } else {
    movieGenreID = (movies %>% filter(grepl(choices[2],genres)))$movieid
    meanUserRatings = ratings %>% filter(movieid %in% movieGenreID)  %>% group_by(userid) %>% summarise(MeanRating = mean(rating))
    head(meanUserRatings)
    
    meanUserRatings = left_join(meanUserRatings,users %>% select(userid,zip),by="userid")
    head(meanUserRatings)
    
    meanUserRatings = meanUserRatings %>% group_by(zip) %>% summarise(rating = mean(MeanRating))
    head(meanUserRatings)
    
  
    meanUserRatings = left_join(meanUserRatings,uszips ,by="zip") %>% select(rating,zip,lat,lng,fips)
    
    meanUserRatings = meanUserRatings %>% filter(!is.na(lat))
    plot = plot_usmap(data = meanUserRatings, values = "rating",labels = (choices[1] == "YES"), label_color = "white")  +  scale_fill_continuous( low = "red", high = "green", name = paste("User Rating for",choices[2],"movies",sep=" "), label = scales::comma ) + theme(legend.position = "right")
    
    
  }
  return(plot)
  
}
```

-   Creare una tabella con ogni votazione associata al zipcode dell'utente

```{r}
(param = ifelse(  ((floor(runif(1)*2)) == 0),"O","G"))
if (param == "O"){
  choices = c(FALSE,workTable$workType[floor(runif(1)*length(workTable$workType))+1])
} else {
  choices = c(FALSE,MLGenres$genre[floor(runif(1)*length(MLGenres$genre))+1])
}
print(paste("Chosen Param:",choices[2],sep=" "))

usersMap(choices,param)

```

# ZIPCODE-GROUPING

### [MAIN APP](../../)

```{r}

countZips = users %>% group_by(zip) %>% summarise(count = n()) %>% left_join(uszips,by="zip") %>% filter(!is.na(lat))

plot_usmap(data = countZips, values = "count",labels = TRUE,label_color = "white") +  scale_fill_continuous( low = "red", high = "green", name = "Number of Users", label = scales::comma ) + theme(legend.position = "right")
 


```
