---
title: "OSCARS"
author: "Damiano Fumagalli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(plotly)
library(tidyr)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
source("../IMPORT/dataScript/oscarsData.r")
source("../IMPORT/dataScript/sequelData.r")
source("../IMPORT/dataScript/grossData.r")
```

# INTERACTIVE PLOT {#interactivePlot}

### [MAIN APP](../../)

```{r}


bestNominees = oscars %>% group_by(title) %>% summarise(nominees = n(),winCount = length(winner[winner]), loseCount = length(winner[!winner]))  %>% arrange(desc(nominees))

bestNomineesGross = inner_join(bestNominees,gross,by="title")
#head(bestNomineesGross)






plot = ggplot(bestNomineesGross, aes(x=year, y=gross, size = nominees, color = license, text=title)) + geom_point(alpha=0.5) + scale_size(range = c(1,5), name="NOMINEES") + scale_color_discrete(labels = c("ALL PEOPLE","OVER 10","OVER 13","OVER 17","UNRATED"))  + theme(legend.position="none")



ggplotly(plot)


#ggplot(bestNomineesGross) + geom_histogram(aes(gross,nominees, fill = license), position = "dodge") + scale_fill_discrete(label = c("ALL PEOPLE","Over 10","Over 13","Over 17","NA"))

```

# NOMINEES

```{r}
bestFilmNominees = oscars %>% group_by(title) %>% summarise(nominees = n(), year = year_film) %>% arrange(desc(nominees))
hist(x = bestFilmNominees$nominees,xlab = "Nominees",main = "Nominees Frequency")
```

```{r}
dati = left_join(bestFilmNominees,gross,by="title") %>% filter(!is.na(gross))
head(dati)
hist(x = dati$nominees,xlab = "Nominees",main = "Nominees Frequency")

ggplot(dati) + geom_point(mapping = aes(nominees,gross,color = license)) + scale_y_log10()
```

### GENRE

```{r}
grossGens = grossGenres$genre
prec = 0
genTop = ""
for (i in 1:length(grossGens)){
  a = nrow(dati %>% filter(grepl(grossGens[i],genre)))
  if (a > prec){
    prec = a
    genTop = grossGens[i]
  }
}
print(paste("Genere Più occorrente nei migliori film",genTop,sep=" : "))

```

### LICENSE / NOMINEES

```{r}
ggplot(dati) + geom_bar(mapping = aes(x=nominees,fill=license),position = "dodge")  + scale_fill_discrete(labels=c("Tutti","Over 10","Over 13","Over 17","NA"))
```

### GENRES / NOMINEES

```{r}
head(dati %>% select(title,genre,nominees))
allgen = grossGenres$genre
genCounts = vector(mode = "integer",length = length(allgen))
for (i in 1:length(allgen)){
  genCounts[i] = nrow(dati %>% filter(grepl(allgen[i],genre)))
}
# generi in ordine decrescente per nominees
allgen[rev(order(genCounts))]
```

## SEQUELS

```{r}
View(sequels)
View(oscars)

oscarsWithSequels = inner_join(sequels %>% select(-genres,-votes,-directors),oscars %>% select(title,year_film),by="title") %>% filter(year == year_film) %>% select(-year_film)  %>% group_by(title) %>% summarise(nominees = n(),year = unique(year),rating = unique(rating),duration = unique(duration), order = unique(order),seriesTitle = unique(seriesTitle)) %>% arrange(seriesTitle)

head(oscarsWithSequels)

# more nominees --> grater rating
ggplot(oscarsWithSequels) + geom_point(aes(nominees,year,colour = rating )) 



# NOMINEES RECEIVED BY SERIESTITLE
head(oscarsWithSequels %>% group_by(seriesTitle) %>% summarise(nominees = sum(nominees)) %>% arrange(desc(nominees)))

```
